### PR TITLE
Env var support

### PR DESCRIPTION
**Pull request by chris-salemove**
https://www.pivotaltracker.com/story/show/104301140

### CODE REVIEW

**Comment by chris-salemove** [comment]
@indrekj fixed 'nill' typo and now use 'let'

**Comment by chris-salemove** [comment]
I've also bumped from version 0.1.0 -> 0.2.0

**Comment by indrekj** [comment]
If you do a version bump, then you also need to do "bundle" and commit the Gemfile.lock

**Comment by indrekj** [comment]
Or you can remove the Gemfile.lock from the repository. It is not needed for gems.

**Comment by urmastalimaa** [comment]
+1 for adding Gemfile.lock to gitignore

**Comment by chris-salemove** [comment]
Removed Gemfile.lock. Jenkins still angry. New message:
```
bundle install --deployment
The --deployment flag requires a Gemfile.lock.
```

**Comment by indrekj** [comment]
+1

**Pull request merged**
